name: Ejecutar Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Build de la imagen Docker
      run: docker build -t miimagen:latest .

    - name: Ejecutar el contenedor Docker
      run: docker run miimagen:latest
